name: Update

on:
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Update
        run: ./update.sh
